# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

log:
  level: debug
  methodname: false
  json: false
  destination: stderr
  file: /tmp/debug.log
  combinedtostdout: true
web:
  apihost: 0.0.0.0:3000
  debughost: 0.0.0.0:4000
  secretkey: the answer to life the universe and everything
  readtimeout: 3s
  writetimeout: 3s
  shutdowntimeout: 3s
  behindproxy: false
debug: true
db:
  filename: C:/Users/randr/OneDrive/Desktop/Tempest/WASA/WASAPhoto/WASAPhoto/mock/wasaphoto.db